### ISSUE TITLE
the program spectrum_similarity_pairwise_GUI-0.1.jar exception

### ISSUE THREAD

**Issue by TututuXi** [compomics/spectrum_similarity#2]
### 1. run a probabilistic based scoring function to compare two given spectra data sets
- my mgf file(two mgf file with the same content)
![image](https://user-images.githubusercontent.com/15766876/37282701-500018de-2630-11e8-8ee1-ec2d3c63ce4a.png)
- my setting
![image](https://user-images.githubusercontent.com/15766876/37282675-3a7c2962-2630-11e8-968f-a3a03c002b83.png)
- program output
```
java -cp .\scoring_pipeline-1.3.jar main.ScorePipelineStarter
2018-03-12 17:15:19 INFO  MainController:474 - starting spectrum similarity score pipeline
2018-03-12 17:15:20 INFO  ScorePipeline:677 - Successfully sent analytics event.
2018-03-12 17:15:20 INFO  ScorePipeline:677 - Successfully sent analytics event.
2018-03-12 17:15:20 INFO  MainController:179 - The version of score.pipeline :1.3
2018-03-12 17:15:20 INFO  MainController:190 - Run is ready to start with NF_None_TR_None_PPR_None_CHR_None_PRECTOL_0_MSRobin.txt for msrobin
2018-03-12 17:15:20 INFO  MainController:191 - Only calculate +/-2 slices up and down: false
2018-03-12 17:15:20 INFO  MainController:256 - a name of an mgf from the spectra.folder=data1.mgf
2018-03-12 17:15:20 INFO  MainController:257 - a name of an mgf from the spectra.to.compare.folder=data2.mgf
10%10%2018-03-12 17:15:20 INFO  MainController:280 - Size of MSnSpectra at spectra.folder=1
2018-03-12 17:15:20 INFO  MainController:281 - Size of MSnSpectra at spectra.to.compare.folder=1
2018-03-12 17:15:20 INFO  MainController:484 - finished spectrum similarity score pipeline
```
### 2. when I was ready to run the program *spectrum_similarity_pairwise_GUI-0.1.jar* to see the result I came the exception **ArrayIndexOutOfBoundsException**, what can I do to solve the problem?
![image](https://user-images.githubusercontent.com/15766876/37275261-a22bc070-2619-11e8-880d-94bae814ca19.png)
```
java  -jar
 .\spectrum_similarity_pairwise_GUI-0.1.jar
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2
        at gui_spectral_match_visualization.MainGUI.prepareTable(MainGUI.java:177)
        at gui_spectral_match_visualization.MainGUI.<init>(MainGUI.java:89)
        at gui_spectral_match_visualization.MainGUI$20.run(MainGUI.java:1060)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Thanks!

**Comment by Genet-Abay** [comment]
can you send me the files, please?

**Comment by TututuXi** [comment]
Yes, you can download the files in [https://drive.google.com/open?id=1bc1pjeYdZKqgUZuWY6IyHUqY2jBAp1aB](https://drive.google.com/open?id=1bc1pjeYdZKqgUZuWY6IyHUqY2jBAp1aB)
the contents of two files are the same!
thanks！

**Comment by Genet-Abay** [comment]
it runs fine and here is the output:

The version of Score.Pipeline is 1.3
Spectrum Title	Charge	PrecursorMZ	Spectrum_Title_Comparison_Dataset	ScoringFunction_Pipeline_NF_0_TR_0_PPR_None_CHR_false_PRECTOL_0.0
Locus:1.1.1.1763.2	2+	400.18626002909855	Locus:1.1.1.1763.2	228.43181179205064
Locus:1.1.1.2555.2	2+	400.2300200290985	Locus:1.1.1.2555.2	279.58800173440756
Locus:1.1.1.2178.2	4+	401.2031400145492	Locus:1.1.1.2178.2	182.74544943364052

**Comment by Genet-Abay** [comment]
One more thing, which version are you using? you can try the newest version by cloning from the github itself, not from the link.

**Comment by TututuXi** [comment]
自动回复：我已收到邮件，谢谢！！
